---
apiVersion: v1
kind: Service
metadata:
  name: kanboard-service
  namespace: kanboard
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: kanboard
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kanboard
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: nginx-deployment
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  namespace: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kanboard
  template:
    metadata:
      labels:
        run: kanboard
    spec:
      volumes:
        - name: kanboard-data
          persistentVolumeClaim:
            claimName: kanboard-data
        - name: kanboard-plugins
          persistentVolumeClaim:
            claimName: kanboard-plugins
        - name: kanboard-ssl
          persistentVolumeClaim:
            claimName: kanboard-ssl
        - name: efs-volume
          persistentVolumeClaim:
            claimName: kanboard-efs
      containers:
        - env:
            - name: DEBUG
              value: 'true'
#            - name: DATABASE_URL
#              value: ''
          name: kanboard
          image: kanboard/kanboard:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: "/var/www/app/data"
              name: kanboard-data
            - mountPath: "/var/www/app/plugins"
              name: kanboard-plugins
            - mountPath: "/etc/nginx/ssl"
              name: kanboard-ssl
            - mountPath: "/var/www/app/efs-data"
              name: efs-volume

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: kanboard-ingress
#  namespace: kanboard
#  annotations:
#    spec.ingressClassName: "traefik"
#spec:
#  rules:
#  - host: kanboard.example.com
#    http:
#      paths:
#      - path: /
#       pathType: Prefix
#        backend:
#          service:
#            name: kanboard-service
#            port:
#              number: 80