apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  namespace: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kanboard
  template:
    metadata:
      labels:
        run: kanboard
    spec:
      containers:
        - env:
            - name: DEBUG
              value: 'true'
#            - name: DATABASE_URL
#              value: ''
          name: kanboard
          image: kanboard/kanboard:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"