apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: KB-cluster
  region: us-east-2         # Remplacez par la région de votre choix
  version: "1.32"

nodeGroups:
  - name: kanboard-worker
    instanceType: t3.medium
    desiredCapacity: 2       # Nombre de nœuds de départ
    minSize: 2               # Taille minimale
    maxSize: 4               # Taille maximale
    ssh:
      allow: true            # Active l'accès SSH
      publicKeyName: "EC2 access"  # Remplacez par le nom de votre clé SSH dans AWS

iam:
  withOIDC: true             # Nécessaire pour les permissions IAM sur EFS et RDS

addons:
  - name: vpc-cni            # Plugin de gestion réseau
    version: latest
  - name: aws-efs-csi-driver
    version: latest
  - name: aws-ebs-csi-driver     # Pour le support des volumes EBS si nécessaire
    version: latest