---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kanboard-data
  name: kanboard-data
spec:
  storageClassName: efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kanboard-plugins
  name: kanboard-plugins
spec:
  storageClassName: efs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: kanboard-ssl
  name: kanboard-ssl
spec:
  storageClassName: efs-storagecla
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
