apiVersion: v1
kind: Service
metadata:
  name: kb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: kanboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80